# Generated by Django 5.2.15 on 2026-07-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_ticket_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
