# Generated by Django 5.2.15 on 2026-07-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ticket_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='needs_email',
            field=models.BooleanField(default=False),
        ),
    ]
