# Generated by Django 5.2.15 on 2026-07-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ticket_needs_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
