# Generated by Django 5.2.15 on 2026-07-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ticket_is_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='purpose',
            field=models.CharField(choices=[('answer_generation', 'Answer generation'), ('embedding', 'Embedding a question')], max_length=30),
        ),
    ]
