# Generated by Django 5.2.15 on 2026-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_aiusagelog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_agent_handling',
            field=models.BooleanField(default=False),
        ),
    ]
